### ISSUE TITLE
npm start err

### ISSUE THREAD

**Issue by bhswallow** [thirdweb-example/cra-javascript-starter#1] opened 2022-05-07 10:19 UTC
localhost:3000

Compiled with problems:X

ERROR in ./node_modules/cipher-base/index.js 3:16-43

Module not found: Error: Can't resolve 'stream' in '/www/web/node_modules/cipher-base'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }

ERROR in ./node_modules/ethereumjs-util/dist.browser/account.js 39:31-48

Module not found: Error: Can't resolve 'assert' in '/www/web/node_modules/ethereumjs-util/dist.browser'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
	- install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "assert": false }

ERROR in ./node_modules/ethereumjs-util/dist.browser/address.js 14:31-48

Module not found: Error: Can't resolve 'assert' in '/www/web/node_modules/ethereumjs-util/dist.browser'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
	- install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "assert": false }

ERROR in ./node_modules/ethereumjs-util/dist.browser/object.js 14:31-48

Module not found: Error: Can't resolve 'assert' in '/www/web/node_modules/ethereumjs-util/dist.browser'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
	- install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "assert": false }

**Comment by jarrodwatts** [comment] 2022-05-08 04:51
Looking into this now, thanks for raising it!

**Comment by jarrodwatts** [comment] 2022-05-08 08:03
This should be fixed now with my latest commit @bhswallow - can you confirm?

**Comment by bhswallow** [comment] 2022-05-19 08:27
thank you

**Comment by armanmamyan** [comment] 2022-05-30 10:14
@jarrodwatts still throws an error :/

**Comment by jarrodwatts** [comment] 2022-05-30 10:19
@armanmamyan thanks for letting us know, looks like the problem is back, so our CRA and Vite examples aren't working currently.  We're looking into it and will get back to you.

**Comment by jarrodwatts** [comment] 2022-06-02 10:52
This is fixed in the latest version of the sdk @armanmamyan

**Closed by jarrodwatts** 2022-06-02 10:52 UTC

**Comment by rbrisita** [comment] 2022-08-30 20:19
This is happening again. I resolved it here: #3. Maybe those steps should be added to documentation until dependencies are updated?
